const forecastsData = [
    {
        title: "US GDP",
        content: "What will US GDP growth be in 2021?",
        dueDate: new Date().toLocaleDateString(),
        forecastsMade: 23,
        probablity: "80% Probablity, Yes",
    },
    {
        title: "Australia CPI",
        content: "What will Australian core inflation be for Q1 2022?",
        dueDate: new Date().toLocaleDateString(),
        forecastsMade: 39,
        probablity: "35% Probablity, No",
    },
    {
        title: "NSW Business Confidence",
        content: "Will New South Wales business confidence improve or fall in 2021?",
        dueDate: new Date().toLocaleDateString(),
        forecastsMade: 22,
        probablity: "75% Probablity, Yes",
    },
    {
        title: "US GDP",
        content: "What will US GDP growth be in 2021?",
        dueDate: new Date().toLocaleDateString(),
        forecastsMade: 51,
        probablity: "29% Probablity, No",
    },
    {
        title: "Australia CPI",
        content: "What will Australian core inflation be for Q1 2022?",
        dueDate: new Date().toLocaleDateString(),
        forecastsMade: 19,
        probablity: "85% Probablity, Yes",
    },
    {
        title: "NSW Business Confidence",
        content: "Will New South Wales business confidence improve or fall in 2021?",
        dueDate: new Date().toLocaleDateString(),
        forecastsMade: 23,
        probablity: "45% Probablity, No",
    },
    {
        title: "US GDP",
        content: "What will US GDP growth be in 2021?",
        dueDate: new Date().toLocaleDateString(),
        forecastsMade: 16,
        probablity: "55% Probablity, Yes",
    },
    {
        title: "Australia CPI",
        content: "What will Australian core inflation be for Q1 2022?",
        dueDate: new Date().toLocaleDateString(),
        forecastsMade: 29,
        probablity: "49% Probablity, No",
    },
    {
        title: "NSW Business Confidence",
        content: "Will New South Wales business confidence improve or fall in 2021?",
        dueDate: new Date().toLocaleDateString(),
        forecastsMade: 42,
        probablity: "60% Probablity, Yes",
    },
    {
        title: "US GDP",
        content: "What will US GDP growth be in 2021?",
        dueDate: new Date().toLocaleDateString(),
        forecastsMade: 27,
        probablity: "15% Probablity, No",
    },
    {
        title: "Australia CPI",
        content: "What will Australian core inflation be for Q1 2022?",
        dueDate: new Date().toLocaleDateString(),
        forecastsMade: 40,
        probablity: "50% Probablity, Yes",
    },
    {
        title: "NSW Business Confidence",
        content: "Will New South Wales business confidence improve or fall in 2021?",
        dueDate: new Date().toLocaleDateString(),
        forecastsMade: 28,
        probablity: "32% Probablity, No",
    },
    {
        title: "US GDP",
        content: "What will US GDP growth be in 2021?",
        dueDate: new Date().toLocaleDateString(),
        forecastsMade: 3,
        probablity: "88% Probablity, Yes",
    },
    {
        title: "Australia CPI",
        content: "What will Australian core inflation be for Q1 2022?",
        dueDate: new Date().toLocaleDateString(),
        forecastsMade: 9,
        probablity: "25% Probablity, No",
    },
    {
        title: "NSW Business Confidence",
        content: "Will New South Wales business confidence improve or fall in 2021?",
        dueDate: new Date().toLocaleDateString(),
        forecastsMade: 43,
        probablity: "79% Probablity, Yes",
    },
    {
        title: "US GDP",
        content: "What will US GDP growth be in 2021?",
        dueDate: new Date().toLocaleDateString(),
        forecastsMade: 24,
        probablity: "35% Probablity, No",
    },
    {
        title: "Australia CPI",
        content: "What will Australian core inflation be for Q1 2022?",
        dueDate: new Date().toLocaleDateString(),
        forecastsMade: 43,
        probablity: "60% Probablity, Yes",
    },
    {
        title: "NSW Business Confidence",
        content: "Will New South Wales business confidence improve or fall in 2021?",
        dueDate: new Date().toLocaleDateString(),
        forecastsMade: 23,
        probablity: "29% Probablity, No",
    },
    {
        title: "US GDP",
        content: "What will US GDP growth be in 2021?",
        dueDate: new Date().toLocaleDateString(),
        forecastsMade: 33,
        probablity: "80% Probablity, Yes",
    },
    {
        title: "Australia CPI",
        content: "What will Australian core inflation be for Q1 2022?",
        dueDate: new Date().toLocaleDateString(),
        forecastsMade: 29,
        probablity: "30% Probablity, No",
    },
    {
        title: "NSW Business Confidence",
        content: "Will New South Wales business confidence improve or fall in 2021?",
        dueDate: new Date().toLocaleDateString(),
        forecastsMade: 23,
        probablity: "78% Probablity, Yes",
    },
]

export default forecastsData;